title: IAcine Smart Contract Analyzer ğŸ”
description: Analyze Ethereum smart contracts using AI, RAG, LangChain, and GPT â€“ with a Streamlit web app and PDF export.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
markdown: kramdown
show_downloads: true
